//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtcApi.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid Id { get; set; }
        public string Account { get; set; }
        public string Address { get; set; }
        public int Confirmations { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string TransactionNumber { get; set; }
        public string Type { get; set; }
    }
}
