//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BtcApi.Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public System.Guid Id { get; set; }
        public string Account { get; set; }
        public decimal Balance { get; set; }
    }
}
